fix fly prod config (#21)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -72,11 +72,7 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - uses: pnpm/action-setup@v4
-
-      - uses: actions/setup-node@v4
-        with:
-          cache: 'pnpm'
+      - uses: ./.github/actions/setup-node
 
       - name: Install
         run: make install_lockfile
@@ -117,6 +113,7 @@ jobs:
       tag: ${{ needs.build.outputs.tag }}
 
   deploy_stage:
+    if: ${{ needs.context.outputs.push == 'true' }}
     needs: [context, build, test]
     permissions:
       contents: read
@@ -127,9 +124,9 @@ jobs:
       environment: stage
       tag: ${{ needs.build.outputs.tag }}
       service: web
-      dry:  ${{ needs.context.outputs.push == 'false' }}
 
   deploy_prod:
+    if: ${{ needs.context.outputs.push == 'true' }}
     needs: [context, build, deploy_stage, test]
     permissions:
       contents: read
@@ -140,7 +137,6 @@ jobs:
       environment: prod
       tag: ${{ needs.build.outputs.tag }}
       service: web
-      dry:  ${{ needs.context.outputs.push == 'false' }}
 
   push_latest:
     needs: [build, context, deploy_prod]
@@ -152,6 +148,10 @@ jobs:
       attestations: write
       id-token: write
     steps:
+      - uses: actions/checkout@v4
+
+      - uses: ./.github/actions/setup-node
+
       - name: Login Docker
         uses: docker/login-action@v3
         with:
@@ -172,4 +172,26 @@ jobs:
           docker pull ${{ needs.build.outputs.tag }}
           docker tag ${{ needs.build.outputs.tag }} ${{ steps.latest_tag.outputs.tag }}
           docker push ${{ steps.latest_tag.outputs.tag }}
+
+  checks:
+    if: always()
+    needs: [deploy_stage, deploy_prod, push_latest]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Context
+        run: |
+          cat <<EOF
+          ${{ toJson(needs) }}
+          EOF
+
+          for key in $(echo '${{ toJson(needs) }}' | jq -r 'keys[]'); do
+            job=$(echo '${{ toJson(needs) }}' | jq -r ".[\"$key\"]")
+            result=$(echo "$job" | jq -r '.result')
+            outputs=$(echo "$job" | jq -r '.outputs')
+            if [ "$result" = "failure" ]; then
+              echo "Job $key failed with result: $result"
+              exit 1
+            fi
+            echo "Job $key completed with result: $result and outputs: $outputs"
+          done
 
